INSERT INTO public.unit_refs (id, description)
VALUES (1, 'teaspoon'),
       (2, 'tablespoon'),
       (3, 'cup'),
       (4, 'pint'),
       (5, 'quart'),
       (6, 'gallon'),
       (7, 'milliliter'),
       (8, 'liter'),
       (9, 'deciliter'),
       (10, 'fluid ounce'),
       (11, 'ounce'),
       (12, 'pound'),
       (13, 'gram'),
       (14, 'kilogram'),
       (15, 'milligram'),
       (16, 'centimeter'),
       (17, 'meter'),
       (18, 'inch'),
       (19, 'foot'),
       (20, 'slice'),
       (21, 'pinch'),
       (22, 'dash'),
       (23, 'clove'),
       (24, 'stick'),
       (25, 'head'),
       (26, 'bunch'),
       (27, 'piece'),
       (28, 'sprig'),
       (29, 'beet'),
       (30, 'centiliter'),
       (31, 'thick slice'),
       (32, 'thin slice'),
       (33, 'corner'),
       (34, 'few'),
       (35, 'few stalks'),
       (36, 'smooth tablespoon'),
       (37, 'heaped tablespoon'),
       (38, 'some'),
       (39, 'possibly'),
       (40, 'extra'),
       (41, 'small cask'),
       (42, 'small bottle'),
       (43, 'large bunch'),
       (44, 'large can'),
       (45, 'large bottle'),
       (46, 'large glass'),
       (47, 'large head'),
       (48, 'large slice'),
       (49, 'large piece'),
       (50, 'large'),
       (51, 'half'),
       (52, 'handful'),
       (53, 'stalk'),
       (54, 'crate'),
       (55, 'small bunch'),
       (56, 'small can'),
       (57, 'small bottle'),
       (58, 'small glass'),
       (59, 'small head'),
       (60, 'small slice'),
       (61, 'small piece'),
       (62, 'small'),
       (63, 'grain'),
       (64, 'more'),
       (65, 'as desired'),
       (66, 'pair'),
       (67, 'packet'),
       (68, 'small packet'),
       (69, 'plate'),
       (70, 'portion'),
       (71, 'percent'),
       (72, 'bar'),
       (73, 'small bowl'),
       (74, 'bowl'),
       (75, 'splash'),
       (76, 'stem'),
       (77, 'stalk'),
       (78, 'strip'),
       (79, 'tablet'),
       (80, 'bar (of chocolate)'),
       (81, 'part'),
       (82, 'heaped teaspoon'),
       (83, 'level teaspoon'),
       (84, 'pot'),
       (85, 'tube'),
       (86, 'bag'),
       (87, 'much'),
       (88, 'little'),
       (89, 'root'),
       (90, 'whole'),
       (91, 'zest'),
       (92, 'knife point'),
       (93, 'glass'),
       (94, 'medium size'),
       (95, 'drop'),
       (96, 'cube'),
       (97, 'sheet'),
       (98, 'thick');
